name: Node CI

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    lint-and-dedupe:
        runs-on: ubuntu-latest

        name: Lint & Deduplicate deps on node 20.x and ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Use Node 20.x
              uses: actions/setup-node@v1
              with:
                  node-version: 20.x

            - name: Install deps and build (with cache)
              uses: bahmutov/npm-install@v1

            - name: Lint codebase
              run: yarn lint

            - name: Deduplicate dependencies
              run: yarn deduplicate:check

    test:
        name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['20.x']
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Install deps and build (with cache)
              uses: bahmutov/npm-install@v1
